name: Rossman _sales_prediction
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1 
      - name: Sales run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          pip install -r requirements.txt
          # Your ML workflow goes here
          #cd scripts 
          #python model.py

          # Write your CML report
        
          cat logistic regression_metrics.txt >> report.md
          cml-send-comment report.md
